---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
  post:
    default_front_matter_template: post
  home:
    default_front_matter_template: home
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
version: 0.38.1
