---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- path: content
  label: Pages
  create: all
- path: content/home
  label: Home
  create: all
  default_front_matter_template: home
- path: content/tags
  label: Tags
  create: all
- path: content/post
  label: Post
  create: all
  default_front_matter_template: post
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
version: 0.38.1
